//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string Notification1 { get; set; }
        public string Worker { get; set; }
        public string Room { get; set; }
        public string TimeStart { get; set; }
        public string TimeEnd { get; set; }
        public string CallToAction { get; set; }
    }
}
