//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int ObjectID { get; set; }
        public int Auth { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
